### ISSUE TITLE
Monitoring Remote Postgres database using Zabbix

### ISSUE THREAD

**Issue by dmjaya** [cavaliercoder/libzbxpgsql#125]
Hi
I'm new to zabbix, I need to monitor **Remote Postgres database using Zabbix**, is any one have a correct document with steps? I try lot but still i'm not able to do it.
P.G version is 9.0 +
Zabbix version is 3.0 +
Zabbix Server running on Ubuntu 18.04

Thanks 
Dinesh

**Comment by cavaliercoder** [comment]
Hi Dinesh, getting started can be difficult, because PostgreSQL is a complicated beast. Please be patient with yourself, and take a look at the documentation here: http://cavaliercoder.com/libzbxpgsql/

Please note that these documents require you to be familiar with Zabbix, so make sure to look at their docs first.

**Comment by dmjaya** [comment]
Hello Cavalir 
Thanks for the quick replying, Ok I'll follow this Link

Thanks 
Dinesh

**Comment by dmjaya** [comment]
Hi Ryan
I'm really fed-up, this is not working i follow your link. Do you have any
other link because this is really hard to configure.

Best Regards,
Dinesh

**Comment by cavaliercoder** [comment]
Yes, databases and their monitoring tools are difficult to configure. This issue page is for features and bugs with the module or documentation. Please raise an issue for the specific problem you are facing our reach out to some of the Zabbix  or PostgreSQL support forums like IRC to walk through the problem with someone.
