### ISSUE TITLE
libzbxpgsql3.0 no data from agent

### ISSUE THREAD

**Issue by jazzraven** [cavaliercoder/libzbxpgsql#132]
Hi.
My configuration:
```
Linux alt-docker.localdomain 4.9.71-std-def-alt0.M80P.1 #1 x86_64 GNU/Linux
zabbix-server-pgsql-3.0.24-alt0.M80P.1
postgresql9.6-9.6.11-alt0.M80P.1
postgresql9.6-server-9.6.11-alt0.M80P.1
zabbix-common-3.0.24-alt0.M80P.1
zabbix-server-pgsql-3.0.24-alt0.M80P.1
zabbix-phpfrontend-apache2-3.0.24-alt0.M80P.1
zabbix-server-common-3.0.24-alt0.M80P.1
zabbix-phpfrontend-apache2-mod_php5-3.0.24-alt0.M80P.1
zabbix-agent-3.0.24-alt0.M80P.1
zabbix-phpfrontend-engine-3.0.24-alt0.M80P.1
```

Zabbix-server, agent, libzbxpgsql, Postgresql - all are on the **SAME** box.

**I have installed libzbxpgsql from sources (because there is no package for my distro).
set up the template, have configured the macros, role etc.
But I cannot get any data in zabbix web-interface.**

```
# /usr/sbin/zabbix_agentd -t pg.modver
zabbix_agentd [26934]: starting agent module libzbxpgsql 1.1.0
zabbix_agentd [26934]: using module configuration file: /etc/zabbix/libzbxpgsql.conf
pg.modver                                     [s|libzbxpgsql 1.1.0, compiled for Zabbix 3.0.24]
```

tried:

```
# sudo -u zabbix zabbix_agentd -p | grep '^pg\.'
.....
"btree"},{"{#OID}":"16568","{#PATH}":"zabbix.public.drules.drules_2","{#INDEX}":"drules_2","{#DATABASE}":"zabbix","{#SCHEMA}":"public","{#TABLE}":"drules","{#OWNER}":"zabbix","{#ACCESS}":"btree"},{"{#OID}":"16567","{#PATH}":"zabbix.public.drules.drules_1","{#INDEX}":"drules_1","{#DATABASE}":"zabbix","{#SCHEMA}":"public","{#TABLE}":"drules","{#OWNER}":"zabbix","{#ACCESS}":"btree"},{"{#OID}":"16565","{#PATH}":"zabbix.public.drules.drules_pkey","{#INDEX}":"drules_pkey","{#DATABASE}":"zabbix","{#SCHEMA}":"public","{#TABLE}":"drules","{#OWNER}":"zabbix","{#ACCESS}":"btree"}]}]
pg.db.size                                    [u|40931404]
pg.table.size                                 [u|2211840]
pg.table.rows                                 [u|20501]
pg.table.children[,,pg_database]              [u|0]
pg.table.children.size[,,pg_database]         [u|0]
pg.table.children.rows[,,pg_database]         [u|0]
pg.index.size                                 [u|7913472]
pg.index.rows                                 [u|87996]
pg.tablespace.size[,,pg_default]              [u|40964172]
pg.namespace.size[,,pg_catalog]               [u|4087808]
....
```
and this:
```
# zabbix_get -s localhost -k pg.db.discovery["host=localhost port=5432 user=monitoring connect_timeout=10",postgres]
{"data":[{"{#OID}":"13016","{#PATH}":"postgres","{#DATABASE}":"postgres","{#ENCODING}":"UTF8","{#LC_COLLATE}":"ru_RU.UTF-8","{#LC_CTYPE}":"ru_RU.UTF-8","{#OWNER}":"postgres","{#TABLESPACE}":"pg_default","{#DESCRIPTION}":"default administrative connection database"},{"{#OID}":"16385","{#PATH}":"zabbix","{#DATABASE}":"zabbix","{#ENCODING}":"UTF8","{#LC_COLLATE}":"ru_RU.UTF-8","{#LC_CTYPE}":"ru_RU.UTF-8","{#OWNER}":"zabbix","{#TABLESPACE}":"pg_default","{#DESCRIPTION}":""}]}
```

in the agent log - nothing special

the macros:
`{$PG_CONN} => host=alt-docker.localdomain port=5432 user=zabbix password=  connect_timeout=10`

pg_hba.conf:
`local   all             monitoring                              ident map=monitoring`

pg_ident.conf:
`monitoring      zabbix  monitoring`

Not sure about .pgpass file. I have made it, but cannot figure out what account put there in (monitoring, zabbix. postgres??)
and I don`t use any pass when doing zabbix_get from console.

Any ideas?

**Comment by i-ky** [comment]
Do items become "not supported"? What is the message? Have you checked server's log file?
It seems that in the template all items have the type _Zabbix agent (active)_, maybe that's the issue?

**Comment by jazzraven** [comment]
> 
> 
> Do items become "not supported"? What is the message? Have you checked server's log file?
> It seems that in the template all items have the type _Zabbix agent (active)_, maybe that's the issue?

In web-interface I don`t see any messages at all. I just can`t see any data from the template on the "last data" screen.
The server`s logs are quiet.
And yes, all items have type _Zabbix agent (active)_
What should I do about it. I changed type of several of the items on just "zabbix" and they became grey on the last data screen.

**Comment by i-ky** [comment]
In _Latest data_ check _Show details_ checkbox. In the _Info_ column you should see red crosses, click on them to the reason why they are "not supported".

**Comment by i-ky** [comment]
Where have you defined this macro? On the host (check it is a correct one), template or globally?
The problem here is that Zabbix server does not resolve it for some reason.

**Comment by jazzraven** [comment]
When I was written my messages it was defined in the Template. When I got your message I delete PG_Conn from the Template and define it in the Host. Still the same

**Comment by jazzraven** [comment]
Does it have anything to do with the pass, and what the user should be in PG_CONN?
I mean all that stuff about .pgpass file and everything.
I have tried different combinations, but it seems nothing works.
Like if I have _user=zabbix_ in PG_CONN, does it mean that I have to put its credentials into .pgpass?
And in whose home directory it should been (of user zabbix too)?
Feel a bit confused...

**Comment by i-ky** [comment]
I'm neither developer nor user of this module, I'm watching this repository for other reasons :)
I don't think these questions matter at this point. Agent works perfectly with `zabbix_get`, your server can get data from server... The problem is - server does not replace macro with its value in the item key, agent rightly reports an error.
1. Double check that the macro is configured in the right place. To test it you can put same macro in item name and see if Zabbix frontend will resolve it.
2. Make sure that Zabbix server has updated its configuration cache from the database since you've added the macro. It's governed by [`CacheUpdateFrequency`](https://www.zabbix.com/documentation/4.0/manual/appendix/config/zabbix_server) parameter or you can force it using [`-R config_cache_reload`](https://www.zabbix.com/documentation/4.0/manual/concepts/server#running_server)
3. To further troubleshoot the issue you can increase logging of Zabbix server using `-R log_level_increase=poller` and see what's happening.

**Comment by cavaliercoder** [comment]
Thanks everyone for working together on this issue. I do recommend that these kinds of issues are better resolved on the Zabbix IRC. Asking here is fine, but responses are high latency and conversation needs to stay confined to this module. If your issue turns out to be unrelated (say, macros or PostgreSQL HBAs) then it seems nonproductive here.

If you spot an issue with the software, packaging or documentation of libzbxpgsql, this is the right place. Though you will note I am a little behind on support, as I no longer use Zabbix or PostgreSQL in my professional life.

**Comment by jazzraven** [comment]
Guys, thanks to everyone.
**Solved!**
Just messed up with $PG_CONN
either misspelled smth there or put it not into the right place.
Anyway, now everything works propely and I got known a lot of new features.
