### ISSUE TITLE
Discovery: item already exists with the same key

### ISSUE THREAD

**Issue by robbrucks** [cavaliercoder/libzbxpgsql#39]
Hey Ryan,

I tried to add two more item prototypes in the "Discover Postgresql Databases" discovery rule using the "pg.query.integer" key to pull in lock wait counts and also idle-in-transaction counts by DB.  But Zabbix is complaining "Cannot create item: item already exists with the same key".

Am I going about this wrong?  Is there something I need to do to make them unique?

I've attached the xml for the new prototypes.

Thanks,
Rob

[new_prototypes.txt](https://github.com/cavaliercoder/libzbxpgsql/files/200655/new_prototypes.txt)

**Comment by cavaliercoder** [comment]
The prototypes you've created don't indicate which database you wish to gather lock stats for. You should use the '{#DATABASE}` macro returned by the discovery rule in one of two ways:

1. Use `{#DATABASE}` as the second parameter; in place of `{$PG_DB}` or
2. Use `datname = '{#DATABASE}'` instead of `current_database()`

**Comment by robbrucks** [comment]
Thanks Ryan!

That did the trick.
