### ISSUE TITLE
Huge amount of TIME_WAIT connections

### ISSUE THREAD

**Issue by aabudari** [cavaliercoder/libzbxpgsql#65]
We are seeing thousands of TIME_WAIT connections after installing this component, could you please advise

**Comment by cavaliercoder** [comment]
At a guess, without further information, these are likely because the PostgreSQL template has discovered thousands of monitored assets, such as tables, indices, etc. As a result, Zabbix will be attempting thousands of connections to gather all this data as the module currently uses one connection per check. Often on Linux and Windows systems, connections sit in TIME_WAIT until the OS cleans them up periodically.

If you want to monitor thousands of metrics, I would recommend using a connection pooler such as  PGBouncer. Otherwise, disable some LLD discovery rules or add some restrictive discovery filters to target the resources you need to monitor. You might also consider reducing the monitoring interval from 60 seconds to 5 minutes.

How many PostgreSQL items have been discovered on your host?

**Comment by cavaliercoder** [comment]
You could also use local unix sockets instead of TCP/IP.

Closing after no response from OP.
